---
name: build
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pipenv
        run: |
          pip install --user pipenv

      - name: Run pipenv
        run: |
          pipenv install

      - name: Compile examples
        run: |
          (cd examples/ping_interval && pipenv run pio run -e esp32 -e esp8266)
